name: ErrLib-CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with MSBuild
      run: |
        $Env:Path += ";${Env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"; msbuild
    - name: Test
      run: |
        Set-Location -Path .\Debug; & "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" ErrLib_Tests.dll
    - name: Archive build results
      uses: actions/upload-artifact@v4
      with:
          name: Output
          path: Debug/
